# Generated by Django 6.0.6 on 2026-06-19 14:47

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(max_length=13, unique=True, validators=[shared.validators.validate_cedula_ec], verbose_name='DNI/RUC'),
        ),
    ]
